const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

const REQUEST_ERROR = "REQUEST_ERROR";
const RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR";
const UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST";

const CLEAR_ERROR = "CLEAR_ERROR";

const FETCH_CATEGORIES = "FETCH_CATEGORIES";

const TOGGLE_THEME = "TOGGLE_THEME";

const LOGOUT = "LOGOUT";

export {
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  REQUEST_ERROR,
  UNAUTHORIZED_REQUEST,
  RESOURCE_NOT_FOUND_ERROR,
  CLEAR_ERROR,
  FETCH_CATEGORIES,
  TOGGLE_THEME,
  LOGOUT,
};
